### ISSUE TITLE
签到成功数量为0

### ISSUE THREAD

**Issue by fxaxg** [PearNoDec/HuluxiaSign#1]

**Comment by PearNoDec** [comment]
![{9AE84848-647B-4bb8-B392-CEF6A1123176}](https://github.com/PearNoDec/HuluxiaSign/assets/125916617/e50dda0f-41c4-416c-b1a7-4e88e74498c5)
我用Key模式没问题噢,登陆模式也一样

**Comment by fxaxg** [comment]
> ![{9AE84848-647B-4bb8-B392-CEF6A1123176}](https://user-images.githubusercontent.com/125916617/258585025-e50dda0f-41c4-416c-b1a7-4e88e74498c5.png) 我用Key模式没问题哦，登陆模式也一样

刚刚成功了，可能是网络问题 感谢作者回复！
